const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'Free-Shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      desription: 'A popular dress.',
    },
    {
      name: 'Free Shirt2',
      slug: 'Free-Shirt2',
      category: 'Pants',
      image: '/images/shirt2.jpg',
      price: 90,
      brand: 'Adidas',
      rating: 8,
      numReviews: 32,
      countInStock: 15,
      desription: 'A popular pant in America.',
    },
    {
      name: 'Super Coat',
      slug: 'Super-Coat',
      category: 'Coats',
      image: '/images/coat1.jpg',
      price: 50,
      brand: 'Raymond',
      rating: 9.5,
      numReviews: 12,
      countInStock: 100,
      desription: 'A popular coat.',
    },
    {
      name: 'Free T Shirt',
      slug: 'Free-T-Shirt',
      category: 'T-Shirts',
      image: '/images/tshirt1.jpg',
      price: 20,
      brand: 'Oliver',
      rating: 5,
      numReviews: 14,
      countInStock: 30,
      desription: 'A popular T shirt.',
    },
    {
      name: 'T Shirt 2',
      slug: 'T-Shirt2',
      category: 'T-Shirts',
      image: '/images/tshirt2.jpg',
      price: 70,
      brand: 'Zara',
      rating: 8,
      numReviews: 15,
      countInStock: 30,
      desription: 'A popular T shirt.',
    },
    {
      name: 'T Shirt 3',
      slug: 'T-Shirt-3',
      category: 'T-Shirts',
      image: '/images/tshirt3.jpg',
      price: 70,
      brand: 'Zara',
      rating: 8,
      numReviews: 15,
      countInStock: 30,
      desription: 'A popular T shirt.',
    },
    {
      name: 'T Shirt 4',
      slug: 'T-Shirt4',
      category: 'T-Shirts',
      image: '/images/tshirt4.jpg',
      price: 70,
      brand: 'Zara',
      rating: 8,
      numReviews: 15,
      countInStock: 30,
      desription: 'A popular T shirt.',
    },
  ],
};

export default data;
